"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var message = 'Hello world';
console.log(message);
var isBeginner = true;
var total = 0;
var name = 'John';
var sentence = "\n  My name is ".concat(name, ",\n  I'm a beginner is TypeScript\n");
console.log(sentence);
var n = null;
var u = undefined;
